### PR TITLE
Renaming Defaults to FieldDefaults

### PR DESCRIPTION
**Pull request by briochemc**
I'm not sure if I'm doing the right thing. So far I just changed every occurrence of "Defaults" to "FieldDefaults" where appropriate I think. I guess creating this pull request will trigger a travis check? I'll try anyway 😄

### CODE REVIEW

**Comment by briochemc** [comment]
Well I don't know how to do the renaming properly I guess :)

**Comment by rafaqz** [comment]
Checks will break cos the repo name is wrong! I'll change the name and merge and it should work

**Comment by briochemc** [comment]
Yeah I was not sure I could do it all myself because of that — I thought you had a secret technique! So is that it? How about putting it into Metadata?

**Comment by rafaqz** [comment]
Done. Sorry I'm travelling and making a release was not so easy on mobile github...

**Pull request merged**
